## **APLIKASI PYTHON PADA MATEMATIKA MATRIKS DAN ALJABAR LINEAR**

In [ ]:
def f(x):
  return x**2 + 2*x + 3


## **Matrix Operation and Transpose**

*   Addition-Substraction
*   Multiplication-Division
*   Scalars





In [ ]:
#MATRIX MULTIPLICATION
import numpy as np


A = np.array ([
    [1, 2, 3], [5, 3, 2]
])

B = np.array ([
    [5, 2, 10], [3, 2, 7], [3,3,3]
])

print(A)
print (B)
print("perkalian dari", A, "x", B, "adalah:", A@B )

#If A = m*n, B must be n*k with m, n, and k are integers



[[1 2 3]
 [5 3 2]]
[[ 5  2 10]
 [ 3  2  7]
 [ 3  3  3]]
perkalian dari [[1 2 3]
 [5 3 2]] x [[ 5  2 10]
 [ 3  2  7]
 [ 3  3  3]] adalah: [[20 15 33]
 [40 22 77]]


In [9]:
#Matrix Division
import numpy as np

A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print("Pembagian dari matrix A dan B adalah", A @ np.linalg.inv(B))

Pembagian dari matrix A dan B adalah [[ 3. -2.]
 [ 2. -1.]]


In [5]:
#MATRIX ADDITION
A = np.array ([
    [1, 2, 3], [5, 3, 2], [5,2,1]
])

B = np.array ([
    [5, 2, 10], [3, 2, 7], [3,3,3]
])

print(A)
print (B)
print("penjumlahan dari", A, "x", B, "adalah:", A+B )

[[1 2 3]
 [5 3 2]
 [5 2 1]]
[[ 5  2 10]
 [ 3  2  7]
 [ 3  3  3]]
penjumlahan dari [[1 2 3]
 [5 3 2]
 [5 2 1]] x [[ 5  2 10]
 [ 3  2  7]
 [ 3  3  3]] adalah: [[ 6  4 13]
 [ 8  5  9]
 [ 8  5  4]]


In [4]:
#SCALAR AND MATRIX
A = np.array ([
    [1, 2, 3], [5, 3, 2], [5,2,1]
])

print(A*10)

[[10 20 30]
 [50 30 20]
 [50 20 10]]


# Determinan and Invers

In [ ]:
import numpy as np

A = ([
    [1, 2, 3], [2,3,4], [5,6,7]
])
det = np.linalg.det(A)
print("Maka determinan ialah", det)
inv = np.linalg.inv(A)
print("Maka invers dari matriks ini ialah", inv)


Maka determinan ialah 1.7763568394002396e-15
Maka invers dari matriks ini ialah [[-1.68884986e+15  2.25179981e+15 -5.62949953e+14]
 [ 3.37769972e+15 -4.50359963e+15  1.12589991e+15]
 [-1.68884986e+15  2.25179981e+15 -5.62949953e+14]]


# Eigenvalues and Eigenvector

In [ ]:
import numpy as np

A = ([
    [1, 2, 3], [2,3,4], [5,6,7]
])

values, vectors = np.linalg.eig(A)

print("Ini adalah eigenvalues:", values)
print("Ini adalah eigenvectors", vectors)


Ini adalah eigenvalues: [ 1.20000000e+01 -1.00000000e+00 -8.40398639e-17]
Ini adalah eigenvectors [[ 0.30996521  0.66666667  0.40824829]
 [ 0.44280744  0.33333333 -0.81649658]
 [ 0.84133414 -0.66666667  0.40824829]]


# Rank Matrix

In [ ]:
import numpy as np

A = ([
    [1, 2, 3], [2, 4, 7]
])

rank = np.linalg.matrix_rank(A)
print("Maka, matrix rank dari matrix ini adalah", rank)

Maka, matrix rank dari matrix ini adalah 2


# Linear Algebra Problem Solving for 2 Variables



> Given such linear problem:
x + 2y = 5
3x + 4y = 11




In [1]:
import numpy as np

A = np.array ([
    [1, 2], [3, 4]
])

B = np.array ([5, 11])

solution = np.linalg.solve(A, B)

print(solution)

[1. 2.]
